//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Specifications.
        /// </summary>
        public static string ComputerSpecifications {
            get {
                return ResourceManager.GetString("ComputerSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Specifications.
        /// </summary>
        public static string GameSpecifications {
            get {
                return ResourceManager.GetString("GameSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        public static string Logins {
            get {
                return ResourceManager.GetString("Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactorers.
        /// </summary>
        public static string Manufactorers {
            get {
                return ResourceManager.GetString("Manufactorers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactorer Types.
        /// </summary>
        public static string ManufactorerTypes {
            get {
                return ResourceManager.GetString("ManufactorerTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Infos.
        /// </summary>
        public static string MapInfos {
            get {
                return ResourceManager.GetString("MapInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Series.
        /// </summary>
        public static string ModelSeries {
            get {
                return ResourceManager.GetString("ModelSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Serie Types.
        /// </summary>
        public static string ModelSerieTypes {
            get {
                return ResourceManager.GetString("ModelSerieTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Language Strings.
        /// </summary>
        public static string MultiLangStrings {
            get {
                return ResourceManager.GetString("MultiLangStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece In Computers.
        /// </summary>
        public static string PieceInComputers {
            get {
                return ResourceManager.GetString("PieceInComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Selectors.
        /// </summary>
        public static string ProductSelectors {
            get {
                return ResourceManager.GetString("ProductSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileSpecific {
            get {
                return ResourceManager.GetString("ProfileSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users In Roles.
        /// </summary>
        public static string UsersInRoles {
            get {
                return ResourceManager.GetString("UsersInRoles", resourceCulture);
            }
        }
    }
}
